version: '3.9'

services:
  bot:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 10s
    env_file:
      - .env
    build: .
    ports:
      - "80:80"
    networks:
      - default
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.paulsbot-http.rule=Host(`bot.paulsgaming.com`)
        - traefik.http.routers.paulsbot-http.entrypoints=http
        - traefik.http.routers.paulsbot-http.middlewares=https-redirect
        - traefik.http.routers.paulsbot-https.rule=Host(`bot.paulsgaming.com`)
        - traefik.http.routers.paulsbot-https.entrypoints=https
        - traefik.http.routers.paulsbot-https.tls=true
        - traefik.http.routers.paulsbot-https.tls.certresolver=le
        - traefik.http.services.paulsbot.loadbalancer.server.port=80
        - traefik.http.routers.paulsbot-https.middlewares=security-headers